github/platform-samples

api/ruby/discovering-resources-for-a-user/Gemfile
api/ruby/discovering-resources-for-a-user/Gemfile.lock
api/ruby/discovering-resources-for-a-user/discovering_organizations.rb
api/ruby/discovering-resources-for-a-user/discovering_repositories.rb

/ping @gjtorikian and @pengwynn for :eyes:

Add samples re: discovering resources for the authenticated user

---

api/ruby/2fa_checker.rb

- uses GITHUB_TOKEN and GITHUB_HOSTNAME environment variables
- improved argument argument & error handling

Improve token handling; add support for GHE endpoints

---

api/ruby/basics-of-authentication/README.md

@gjtorikian @nathos @jasonrudolph
Hi guys, :smile: 
I add a second header to **`api/ruby/basics-of-authentication/README.md
`** for a better overview.
*Yours,*
[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat:

Add header

---

api/ruby/traversing-with-pagination/changing_number_of_items.rb
api/ruby/traversing-with-pagination/constructing_results.rb
api/ruby/traversing-with-pagination/navigating_results.rb

Improve regex for octokit pagination examples github/developer.github.com#936

Improve regex for octokit pagination examples

---

api/groovy/AuditUsers.groovy
api/groovy/ListReposInOrg.groovy
api/groovy/MigrateRepositories.groovy

* Adding script to export GitHub.com repositories to GitHub Enterprise
* Adding script to show all repositories a given set of users can access on a GitHub Enterprise instance

Adding groovy examples on how to use our API

---

README.md
graphql/Gemfile
graphql/Gemfile.lock
graphql/README.md
graphql/bin/run-query
graphql/queries/repositories_with_stargazers.graphql
graphql/queries/viewer.graphql

I thought it'd be good to add a few simple GitHub GraphQL API queries into this repository. :sparkles:
cc @gjtorikian

Add GraphQL query examples

---

pre-receive-hooks/block_ip_range.sh

As requested by @jonico in https://github.com/github/services/issues/2248#issuecomment-245660958

Add IP address range blocker script

---

pre-receive-hooks/block_unknown_pushers.sh

Pre-receive hook that will block any pushes  repository modifications not performed by a user in the list (foo, bar, foobar)

Hook to block pushes from non-white-listed users

---

README.md

Typo, fixes https://github.com/github/platform-samples/issues/117.
/cc @harshithachidanand

{developers → developer}.github.com

---

api/ruby/enterprise/list_issue_attached_files.rb

This is a sample script to list all files attached to issues and pull requests.

Script to list all files attached to issues and PRs

---

pre-receive-hooks/block_self_merge_prs.sh

This corrects some Bash syntax errors that prevent this hook script from working as intended.

Fix block self-merge script

---

api/python/building-a-ci-server/server.py

Add Python'3 print function so it supports both Python2 and Python3 out of the box.

Python 3 support

---

api/ruby/find-inactive-members/README.md

Small change in `README.md` to correct the script name

Small Documentation Update

---

pre-receive-hooks/always_reject.sh

The error message to the user was not really very helpful.
Expand the error message so that it adds a bit more information.

Make the error message more meaningful.

---

graphql/queries/org-members-by-team.graphql
graphql/queries/pr-merged-info-by-repository.graphql
graphql/queries/repo-get-all-branches.graphql

Added a few of the queries I wrote for a client to build out a metric dashboard:
- Organization Members grouped by Team
- Merged PR Information for a given Repository
- All existing branches for a given Repository

Adding additional queries

---

hooks/jenkins/jira-issue-validator/jira-issue-validator.Jenkinsfile
hooks/jenkins/jira-issue-validator/jira-issue-validator.md
hooks/jenkins/master-branch-protect/branch-protect.Jenkinsfile
hooks/jenkins/master-branch-protect/branch-protect.md

These two pipelines provide examples on how to use Jenkins to protect branches and to validate JIRA issues

Jenkins pipeline samples

---

hooks/python/flask-github-webhooks/Dockerfile
hooks/python/flask-github-webhooks/README.md
hooks/python/flask-github-webhooks/config.json.sample
hooks/python/flask-github-webhooks/hooks/example
hooks/python/flask-github-webhooks/requirements.txt
hooks/python/flask-github-webhooks/webhooks.py

Added a Flask webhook server example

Flask webhook samples

---

api/bash/migrate-repos-in-org.sh
api/bash/repo-name-collision-detection.sh
api/bash/repo-sizer.sh

added scripts used to help migrate repos, validate collisions, and get size of a repo on disk. These scripts can be used by other hubbers to help get basic data and update for a user

Add awkbar scripts

---

api/bash/delete-empty-repos.sh

This adds a script to list, and delete (if desired) empty repositories from an organization on a GitHub Enterprise instance.
Empty is denoted by the `size` attribute in the JSON response from the GET API call to get the repositories information. [Documentation](https://developer.github.com/v3/repos/#get). This attribute is `0` when the repository is not initialized, or initialized by has no content (empty README, etc).

Add iamhughes bash script

---

graphql/enterprise/package.json

The following vulnerabilities are fixed with an upgrade:
- https://snyk.io/vuln/npm:marked:20170112
- https://snyk.io/vuln/npm:marked:20170815
- https://snyk.io/vuln/npm:marked:20170815-1
- https://snyk.io/vuln/npm:marked:20170907
- https://snyk.io/vuln/npm:marked:20180225
- https://snyk.io/vuln/npm:react-dom:20180802

fix: graphql/enterprise/package.json to reduce vulnerabilities

---

api/python/building-a-ci-server/requirements.txt
api/python/building-a-ci-server/server.py

This add an example on how to response to a webhook ping.
https://developer.github.com/webhooks/#ping-event

feat: Add webhook ping response

---

api/bash/delete-empty-repos.sh

'delete-empty-repos.sh' error handling

---

hooks/jenkins/jira-workflow/.github/jira-workflow.yml
hooks/jenkins/jira-workflow/Jenkinsfile
hooks/jenkins/jira-workflow/README.md

This pipeline example shows how users can create release branches in GitHub from Jira, as well as generate releases in GitHub by releasing a version in Jira.

Create jira-workflow example

---

README.md
scripts/README.md
scripts/git-change-author
scripts/git-find-dirs-deleted-files
scripts/git-find-dirs-many-files
scripts/git-find-dirs-unwanted
scripts/git-find-ignored-files
scripts/git-find-large-files
scripts/git-find-lfs-extensions
scripts/git-find-utf-16-encoded-files
scripts/git-normalize-pathnames
scripts/git-purge-files

This way the scripts might have a greater visibility 👍 
https://github.com/larsxschneider/git-repo-analysis

move scripts over from git-repo-analysis

---

hooks/jenkins/jira-workflow/Jenkinsfile

This PR looks up related issues in a Jira Release Version and adds them to the description of a GitHub Release

Add Jira issues to GitHub release description

---

api/bash/delete-empty-repos.sh

This change is an attempt to address https://github.com/github/platform-samples/issues/190

Add support for paginated responses

---

app/ruby/app-issue-creator/Gemfile
app/ruby/app-issue-creator/Gemfile.lock

Adding activesupport gem

---

api/ruby/find-inactive-members/find_inactive_members.rb

* private forks created to discuss and mitigate security advisories did work with find_incative_members.rb
* readson: GitHub's API returns 404 (not found) instead of an empty set for issues and issue comments of such a private fork if no access is granted
* fix: ignore 404 for issues and issue comments and proceed

find_inactive_members works with advisories

---

api/ruby/find-inactive-members/README.md

I tried to write a simpler definition of Inactivity. Not sure if I succeeded?
Please take a look.

[docs] simplify definition of Inactivity

---

hooks/jenkins/master-branch-protect/README.md

I had my username changed from `Hollyw0od` to `Hollywood` so I just updated the text in the `README` to reflect that.

Update master-branch-protect README

---

README.md

Update Readme. file

---

api/powershell/invite_members_to_org.ps1

Make it clear that the script is for Enterprise Cloud customers

Update script description
