github/platform-samples

- api/bash/README.md
- api/bash/get-status
- api/bash/plumbing
- api/bash/pretty-print
I had some time today to work through the add-shell-scripts branch and make some changes I've been thinking about. I thought @nathos' script was really neat -- Perhaps it's slightly less approachable than the other scripts here, so I have made an effort to simplify it.
* Refactored `gh_request` from `pretty-print` into a new`plumbing` method: `github_get`
* Refactored `pretty-print` to use plumbing
* Added helper methods for setting user or repository context, outputting whitespace and pretty-printed headers
* Added `get-status` script
* Added some documentation about `set-status` and `get-status` scripts, as well as the required `GH_TOKEN`.
* Refreshed documentation to point users at the `./pretty-print -h` method -- Since this script already has a built in menu, I figured that may be …
> Refactor shell scripts

- api/ruby/team_audit.rb
This allows an admin to get a CSV output of all members and repositories for all teams within an organization.
**Usage:**
```shell
export GITHUB_TOKEN=0000000000000000000000000000
export GITHUB_API_ENDPOINT=https://github.example.com/api/v3
ruby team_audit.rb my_org
```
The script will create a date-stamped directory for the organization and populate it with 2 CSV files per team on that organization (one for members and one for repos). If the script is run a second time in the same day, the previous output will be overridden.
> Create a script for auditing team members and repos

- api/ruby/user-auditing/README.md
- api/ruby/user-auditing/suspended_user_audit.rb
- api/ruby/user-auditing/user_audit.rb
Lists total number of active, suspended, and recently suspended users. Gives the option to unsuspend all recently suspended users. This is mostly useful when a configuration change may have caused a large number of users to become suspended.
> add user audit

- api/ruby/2fa_checker.rb
- api/ruby/instance-auditing/instance_auditor.rb
- api/ruby/team_audit.rb
A handful of scripts include references to `http://api.github.com`. In order to use api.github.com, requests must be made via HTTPS, not HTTP.
This pull request replaces all instances of `http://api.github.com` with `https://api.github.com` so that [developers reading these scripts don't run into issues](http://stackoverflow.com/questions/33082535/no-connection-could-be-made-to-github#comment53982393_33082535) trying to use HTTP instead of HTTPS. 
```
$ curl -v http://api.github.com
* Rebuilt URL to: http://api.github.com/
*   Trying 192.30.252.124...
* connect to 192.30.252.124 port 80 failed: Connection refused
* Failed to connect to api.github.com port 80: Connection refused
* Closing connection 0
```
/cc @kylemacey @gjtorikian for review
> Use HTTPS (not HTTP) for api.github.com

- api/ruby/building-a-ci-server/Gemfile
- api/ruby/building-a-ci-server/Gemfile.lock
- api/ruby/delivering-deployments/Gemfile
- api/ruby/delivering-deployments/Gemfile.lock
- api/ruby/rendering-data-as-graphs/Gemfile
- api/ruby/rendering-data-as-graphs/Gemfile.lock
- hooks/ruby/configuring-your-server/Gemfile
- hooks/ruby/configuring-your-server/Gemfile.lock
Initially only the basics-of-authentication Gemfile had an entry: `gem "json",        "~> 1.8"`.
This merge corrects all Gemfiles in the repo that use json to require `"~> 1.8"`. Also all the Gemfile.lock files were regenerated.
> Update all Gemfiles to use json 1.8+

- api/ruby/rendering-data-as-graphs/README.md
@gjtorikian @nathos @kylemacey / @github
----
> **[*Rack*](https://github.com/rack/rack) requires `bundle exec ...` command!**
Because if we run `rackup -p 4567`, we get this error output:
```powershell
C:\Users\Suriyaa\Downloads\PROJECTS\RUBY\rendering-data-as-graphs>rackup -p 4567
Gem::LoadError: You have already activated rack 1.6.4, but your Gemfile requires rack 1.5.2. Prepending `bundle exec` to your command may solve this.
block in setup at C:/Ruby/jruby-9.0.5.0/lib/ruby/gems/shared/gems/bundler-1.12.3/lib/bundler/runtime.rb:35
each at org/jruby/RubyArray.java:1560
each at C:/Ruby/jruby-9.0.5.0/lib/ruby/stdlib/forwardable.rb:183
map at org/jruby/RubyEnumerable.java:800
setup at C:/Ruby/jruby-9.0.5.0/lib/ruby/gems/shared/gems/bundler-1.12.3/lib/bundler/runtime.rb:20
setup at …
```
> Rack requires `bundle exec` command

- api/ruby/ghe-org-permissions-report.rb
Adding a script that can utilize the Octokit library to generate a report listing all organizations, their repositories, collaborators, effective permissions, teams, and team permissions.
This repository seems like a good place for this Organization report script to live!
> Add Full Organization Report

- pre-receive-hooks/block_branch_names.sh
To ensure branch names follow a specific rule.
This sample script returns `1` when the branch name contains other than lower case alphabetical characters.
> Pre-receive hook script to block pushes with a specific branch name

- pre-receive-hooks/restrict-master-to-gui-merges.sh
This sample pre-receive hook script will block any changes to the default branch that are not made via Pull Request.
> add script to restrict changes on default branch to PRs

- api/groovy/ListMembersInOrgs.groovy
* groovy script to show all members (that are visible to the personal access token) of the specified GitHub organizations
* The script will first print all visible members of each org individually, then provide a summary for all orgs
* Run 'groovy ListMembersInOrgs.groovy' to see the list of command line options
*  First run may take some time as required dependencies have to get downloaded, then it should be quite fast
*  If you do not have groovy yet, run 'brew install groovy'
> Groovy script to list all visible members in orgs

- api/ruby/basics-of-authentication/views/basic.erb
After login to an account without a public e-mail address I get this error:
```
NoMethodError at /callback
undefined method `empty?' for nil:NilClass
file: basic.erb location: block in singleton class line: 3 
```
Adding a check for `!email.nil?` resolves it.
> added nil check for email

- api/PrintRepoAccess.groovy
Groovy script to show all users that can access a given repository in a GitHub Enterprise instance
* Run 'groovy PrintRepoAccess.groovy' to see the list of command line options
*  First run may take some time as required dependencies have to get downloaded, then it should be quite fast
*  If you do not have groovy yet, run 'brew install groovy'
> Print who has access to a set of repos

- hooks/ruby/dismiss-review-server/Gemfile
- hooks/ruby/dismiss-review-server/Gemfile.lock
- hooks/ruby/dismiss-review-server/README.md
- hooks/ruby/dismiss-review-server/server.rb
Modified the [`configuring-your-server`](https://github.com/github/platform-samples/tree/master/hooks/ruby/configuring-your-server) server to listen for `push` webhook events and cancel any `APPROVED` reviews.
> Add Ruby webhook server to dismiss reviews

- pre-receive-hooks/block_branch_names.sh
Fixed pattern matching to accept only lower case characters and not to block tags
- [Fix] Pattern matching [a-z] did match also upper case characters
- [Fix] Tags were always blocked
> Fixed pattern matching in block_branch_names.sh

- hooks/ruby/delete-repository-event/Gemfile
- hooks/ruby/delete-repository-event/Gemfile.lock
- hooks/ruby/delete-repository-event/README.md
- hooks/ruby/delete-repository-event/app.rb
This webhook will:
- Use the [`RepositoryEvent`](https://developer.github.com/enterprise/v3/activity/events/types/#repositoryevent) [GitHub Enterprise Webhook](https://developer.github.com/enterprise/webhooks/) to listen for `"action": "deleted",`
- Send a notification by creating an issue in a repository when triggered
- Link the archived repository in the issue
cc @azizshamim @ebassias 
To do:
> Add delete repository event webhook

- pre-receive-hooks/require-jira-issue.sh
This pre-receive hook checks that a Jira issue is present in the commit message. The regex pattern I used is `/*\[jira-.*\]` which would match `[jira-1234]`, for example.
/cc @webdog resident regex guru
/cc @MikeNwin who had the 💡 to add this
/cc @osowskit who helped me on this
/cc @github/solutions-engineering bc ❤️ 
Would love all ya'll's feedback on this 📣🐦
> Pre-receive hook that checks for Jira Issue

- api/ruby/discovering-resources-for-a-user/discovering_organizations.rb
Organizations Membership API is out of preview. This is no longer required.
> Removing preview media type

- api/ruby/enterprise/change-domains-in-links.rb
Using the [list_issue_attached_files](https://github.com/github/platform-samples/blob/master/api/ruby/enterprise/list_issue_attached_files.rb) script as a template, this implementation finds images that have been linked, then changes the domain name based on arguments passed in via command line, like so:
```shell
$ ruby change-domains.rb old_domain new_domain
```
By design, this does not rename anything in the body of the comment that isn't a link, allowing you to ensure images render while keeping comment history about the old domain untouched.
> Update the domain name for links in Issue & PR comments

- pre-receive-hooks/block_branch_names_not_starting_with_userID.sh
I get asked about branch naming conventions a lot - so I usually show this as a pre-receive hook.
There is one caveat: this comparison is currently case sensitive.
> Affrae add block_branch_names_not_starting_with_userID.sh

- api/ruby/find-inactive-members/README.md
- api/ruby/find-inactive-members/find_inactive_members.rb
This PR adds a ruby utility to find inactive users in an organization and, optionally, remove them.
It was inspired/necessitated by https://github.com/github/solutions-engineering/issues/5102
As it is based on Octokit.rb (and thereby the REST v3 API) it has the potential to get quite chatty with larger organizations and may require a temporary bump in the API rate limit if using .com
For a full understanding of how it is designed to work, check out the [rendered README](https://github.com/github/platform-samples/blob/find-inactive-members/api/ruby/find-inactive-members/README.md)
> add find-inactive-users

- api/ruby/basics-of-authentication/server.rb
I am going through the setup https://developer.github.com/v3/guides/basics-of-authentication and noticed this small typo.
> Changing rest_client to rest-client

- pre-receive-hooks/commit-current-user-check.sh
The variable "GHE_URL" was quoted incorrectly as "GHE URL"
> Fix syntax error in commit-current-user-check.sh

- pre-receive-hooks/restrict-master-to-gui-merges.sh
There is a bug in `restrict-master-to-gui-merges.sh` that can be exploited to allow you push to master.  All you have to do is push multiple ref updates in one go:
```
$ git push origin HEAD:something HEAD:master     
Counting objects: 1, done.
Writing objects: 100% (1/1), 178 bytes | 0 bytes/s, done.
Total 1 (delta 0), reused 0 (delta 0)
To <internal>:dfox/demo-repo.git
7611f36..b8b8786  HEAD -> master
7611f36..b8b8786  HEAD -> something
$ git rev-parse origin/master
b8b8786e915374f91805b8fc4aebc3091f9aed73
```
The script's use of `exit 0` means it jumps out of the `while` loop and never checks any further refs if the first one is deemed to be valid.  Switching to use `continue` ensures that the script goes round the loop until there's no more input, when it will finally exit 0.
I …
> Bug in restrict-master-to-gui-merges.sh allows merge to master

- pre-receive-hooks/force_push_restricted_branches.sh
This script restricts force pushes to repository, except to branches with a naming pattern of `scratch/*` or `test/*`. 
/cc @djdefi
> add script to restrict force pushes to designated branches

- graphql/enterprise/index.html
Fixes #174 
The way this was constructing the API URL before was not very scalable. There are use cases where hostnames can be much longer than normal. This explicitly checks to see if GraphiQL is being served from the `pages` subdomain, which mans subdomain isolation is enabled. Otherwise, the regular `location.hostname` will be the right URL.
> Explicitly check for subdomain isolation to make sure all URLs work

- api/javascript/enable-org-security-alerts.md
GitHub's product and services teams got together to write a script that enables security vulnerability alerts all at once for a given organization. This helps organizations that predate the launch of vulnerability alerts catch up with enabling them on all of their repositories at once. This file links to the public repository where they are maintained under an MIT license. 
Examples provided are in both Node and Bash. The v3 (REST) APIs used are currently in preview at this time and we expect support for GitHub Enterprise Server as early as GHES 2.18.
> Link to org security alerts script example

- scripts/git-append-commit-trailer
Append a trailer with the commit hash to every commit message.
This can be useful if you rewrite the history later on and you want
to preserve the original commit hashes.
> add git-append-commit-trailer script

- scripts/git-find-stale-branches
Find unmerged branches that haven't been modified for more than a year.
Although branches are cheap in Git, they can clutter the repository in
large quantities. Unmerged branches also might introduce large files
that are unnecessarily kept in the repository. If those branches get
deleted, than Git can cleanup those files automatically.
If you are curious, here is the result for this repo:
```
$ git-find-stale-branches
origin/add-shell-scripts (4 years, 2 months ago)
origin/gjtorikian-patch-1 (2 years, 2 months ago)
origin/org-users-and-collaborators (1 year, 5 months ago)
origin/graphql/issue-utils (1 year, 2 months ago)
origin/primetheus/pre-commit (1 year, 2 months ago)
```
/cc @github/services-devops-engineers
> add script `git-find-stale-branches`

- hooks/jenkins/jira-workflow/README.md
Although it does the exact same behavior, the use of a cmdlet as opposed to direct class instantiation is preferred/best practice.
> Update GUID generations for PowerShell

- api/golang/basics-of-authentication/README.md
- api/golang/basics-of-authentication/server.go
- api/golang/basics-of-authentication/views/basic.tmpl
- api/golang/basics-of-authentication/views/index.tmpl
This is the sample project built by following the "[Basics of Authentication][basics of auth]"
guide on developer.github.com - ported to Go.
As the Go standard library does not come with built-in web session handling, only the [simple example](https://github.com/github/platform-samples/blob/master/api/ruby/basics-of-authentication/server.rb) was ported. The example also shows how to use the [GitHub golang SDK](https://github.com/google/go-github).
First, of all, you would need to [follow the steps](https://developer.github.com/v3/guides/basics-of-authentication/#registering-your-app) in the GitHub OAuth Developer Guide to register an OAuth application with callback URL `http://localhost:4567/callback`.
Copy the client id and the secret of your newly created app and set them as …
> GitHub OAuth Example in Go

- pre-receive-hooks/require-jira-issue.sh
The new version should handle deleted/new branches better and I added a link to help the user fixing the problem.
/cc @github/services-devops-engineers
> improve pre-receive-hook that checks commit messages

- graphql/queries/audit-log-api-example.graphql
This pull request adds an example of querying the audit log via GraphQL, originally in [this gist](https://gist.github.com/jonico/abf33f4bf642bdceca197b9e0ee1de15). 
cc @jonico for review and merge 👀
> Add @jonico's audit log api graphql example

- scripts/boostrap/boot
- scripts/boostrap/boot.bat
- scripts/boostrap/create-bootstrap
The `create-bootstrap` script searches a repository for smallish LFS
files, combines them into larger LFS files, and adds them to a new
orphan branch called `bootstrap`. In addition, the script adds a `boot`
script to the orphan branch which splits the larger LFS files up, again.
In order to leverage the Git LFS pack files, the Git user needs to get
the `bootstrap` branch and run the `boot` script.
/cc @github/services-devops-engineers
> add bootstrap script to download small LFS files efficiently

- graphql/queries/enterprise-sso-member-details.graphql
When an organization has SSO setup through their unified identity enterprise, this query will list all members that have logged in through their idP including their login and email.
> Add query to list member email and logins for an Enterprise

- graphql/queries/12-members-with-scim-identity-org.graphql
- graphql/queries/13-members-with-scim-identity-enterprise.graphql
Last month a couple of times people reached out to me and GitHub to ask how to tie organization members to their SCIM identity using our API. 
Previously I shared [a gist](https://gist.github.com/SvanBoxel/06f541b25aab31b7ce19c0f60bcbee4f), but this repository is a better place for these things. 😄
> GraphQL query showing members with linked SCIM identity

- api/groovy/AuditUsers.groovy
- api/groovy/PrintRepoAccess.groovy
* bumped library number
* introduced -c parameter to support reading repository names/users from CSV 
files exported by GitHub Enterprise Servers' ```stafftools/reports``` page
* introduced -p parameter for additional permission based information
/cc @brntbeer as this modification was done for a common customer
> Better permission reporting and CSV file support for groovy examples

- api/ruby/find-inactive-members/README.md
fix path typo from 
```
cd api/ruby/find-inactive-members
```
to
```
cd platform-samples/api/ruby/find-inactive-members
```
> Fix path in code snippet example

- graphql/queries/users-in-org-with-sso.graphql
Graphql query Returns members of an organization and their associated saml identity. If no saml identity, returns null.
> GraphQL query for Users in an Organization with SSO enabled

- api/ruby/find-inactive-members/find_inactive_members.rb
Fixes the broken CSV generation for find_inactive_members.rb (see issue #308).
Also adds column names to the CSV output.
> Fix CSV generation for find_inactive_members.rb

- README.md
Update the link to the graphQL API from early access to the v4 url fixing the link
> Fix GraphQL link in README.md

- api/ruby/find-inactive-members/README.md
This tool can send a relatively large number of API requests. If not authenticated, the tool may not be able to complete even a single run. Add information about why this happens, and give the user information about how to generate the token.
I work for a soon-to-be enterprise client and needed to run this tool to help determine how many seats we need to license. Including this information in the README would have saved me some time.
> Add more information on OCTOKIT_ACCESS_TOKEN to README.md

- pre-receive-hooks/reject-commits.sh
This can be a useful pre-receive hook if you rewrote the history of a repository and you want to ensure nobody pushes the old commits again.
> add hook to reject certain commits from being pushed to the repository

- api/ruby/find-inactive-members/README.md
Various documentation fixes & improvements
> Jdweiner526 docfix 1

- scripts/git-find-large-files
I ran the `git-find-large-files` command with a `-h` 😁 and ended up with ...
```
./git-find-large-files: line 67: [: -h: integer expression expected
./git-find-large-files: line 67: [: -h: integer expression expected
./git-find-large-files: line 67: [: -h: integer expression expected
...
```
The added check also prevents negative integers.
> added input check and usage to `git-find-large-files` 

- api/bash/create-teams.sh
This PR adds a bash script to create teams in bulk to help Org owners to get up and running when setting up teams as part of their migration effort.
> Add script for creating teams in bulk in github orgs

- api/powershell/invite_members_to_org.ps1
Hi! 👋
This is a script meant to help Enterprise customers batch invite consumed licenses to a given organization. The intent is to reduce friction when there's a need to invite multiple emails/accounts to an organization.
Ultimately, the script is not particular to enterprises, since any user that creates a CSV with a column named "Handle or email" can batch import members to an org as well.
> Add PowerShell script to batch invite members to org

- graphql/queries/search-for-issue-or-bug-requests.graphql
This query will provide a 'paper trail' of Issues and PRs pertaining to a particular Issue when passing in a GitHub Search string. It's useful when trying to determine what requests may still be outstanding vs what requests are actively being worked on.
> Add query to search for Issues & associated PRs/Issues

- pre-receive-hooks/block-outdated-clients.sh
Adds the outdated clients pre-receive hook
> Adds block-outdated-clients pre-receive hook

- README.md
- sql/README.md
- sql/USAGE.md
- sql/audit/admin-tokens.sql
- sql/audit/authorizations.sql
- sql/audit/deploy-keys.sql
- sql/audit/github-apps.sql
- sql/audit/hooks-repos.sql
- sql/audit/hooks-users.sql
- sql/audit/oauth-apps.sql
- sql/audit/user-emails.sql
- sql/audit/user-ssh-keys.sql
- sql/metrics/actions-summary.sql
- sql/metrics/commit-count.sql
- sql/metrics/commit-summary.sql
- sql/metrics/count-tabs.sql
- sql/metrics/issue-report.sql
- sql/metrics/issue-summary.sql
- sql/metrics/linguist-report.sql
- sql/metrics/linguist-stats.sql
- sql/metrics/most-recent-active-repos.sql
- sql/metrics/pr-report.sql
- sql/metrics/prereceive-hooks.sql
- sql/metrics/public-repo-owners.sql
- sql/metrics/reactions-stats.sql
- sql/metrics/staff-notes.sql
- sql/metrics/user-report.sql
- sql/security/active-repo-report.sql
- sql/security/vuln-critical-count.sql
- sql/security/vuln-report.sql
This PR contains a lot of SQL scripts, with directions and detailed comments, to run against GitHub Enterprise Server for custom reporting around auditing, security alerts, and general metrics.  These are currently in use at Booz Allen to provide reporting not available via the API.
> Add SQL queries for GitHub Enterprise Server

- .github/workflows/combine-prs.yml
As this repo has fallen a bit behind on Dependabot updates, and has many pending, I am proposing adding a `workflow_dispatch` based Actions workflow that can help combine multiple PRs into one. This is useful for batching Dependabot updates into a single PR.
> Adds a "combine PRs" workflow to help catch up on Dependabot

- pre-receive-hooks/restrict-master-to-cli.sh
Similar / opposite idea as https://github.com/github/platform-samples/blob/master/pre-receive-hooks/restrict-master-to-gui-merges.sh
This prevents edits via the web UI file editor from saving an edit to a specified branch:
> Create example hook to reject web UI blob edits to a specific branch

- graphql/queries/org-audit-log-api-example.graphql
This pull request changes the reference to the `BusinessAuditEntryData` interface in the audit log example query to the `EnterpriseAuditEntryData` interface, as this reflects the renaming of the interface on the GitHub GraphQL API
https://docs.github.com/en/graphql/reference/interfaces#enterpriseauditentrydata
The change includes an update to the `businessUrl` field to the `enterpriseUrl` field, as that field has been renamed on the interface as well.
Relevant changelog entry https://docs.github.com/en/graphql/overview/changelog#schema-changes-for-2019-07-17
> Changing BusinesAuditEntryData to Enterprise

- api/bash/app-installs.sh
This pull request introduces a new Bash script, `app-installs.sh`, in the `api/bash` directory. The script is used to fetch the first 50 organizations of an enterprise and print the installations for each organization. It uses the GitHub CLI (`gh`) to execute a GraphQL query and make requests to the GitHub API.
Key changes:
* [`api/bash/app-installs.sh`](diffhunk://#diff-67922fd1739fbce0c1aa4039397a2164a84aa51084047bbc5ff21c9767f8dcd7R1-R34): Added a new Bash script that uses a GraphQL query to fetch the first 50 organizations of an enterprise. It iterates over each organization and prints the installations for that organization. The script uses the GitHub CLI (`gh`) to execute the GraphQL query and make requests to the GitHub API.
> Added bash script to query an enterprise for app installs.

- graphql/queries/enterprise-saml-identities-filtered-by-nameid.graphql
- graphql/queries/org-saml-identities-filtered-by-nameid-username.graphql
This PR creates two new sample GraphQL queries for GHEC non-EMUs:
- `org-saml-identities-filtered-by-nameid-username.graphql`
- `enterprise-saml-identities-filtered-by-nameid.graphql`
These queries can be used to find a stored external identity that has a specific SAML `nameId` or SCIM `userName` value. 
For example, this can help an enterprise or organization owner identity the root cause when a user receives the error message below (basically, it can show which GitHub user is already linked to the external identity in the organization/enterprise):
> Your GitHub user account [GitHub username] is currently unlinked. However, you are attempting to authenticate with your Identity Provider using [IdP user account] SAML identity which is already linked to a different GitHub user account in …
> Creating new filtered SAML linked identity queries for GHEC non-EMUs

- pre-receive-hooks/README.md
This pull request adds a note to the `pre-receive-hooks/README.md` file, recommending the use of GitHub Enterprise features like Rulesets and Secret Protection as alternatives to pre-receive hooks.
> Updates hooks section to mention rulesets
